import streamlit as st
from pathlib import Path

# =====================================================
# Page Config
# =====================================================

st.set_page_config(
    page_title="About Project",
    page_icon="ℹ️",
    layout="wide"
)

# =====================================================
# Paths
# =====================================================

BASE_DIR = Path(__file__).resolve().parent.parent

css_path = BASE_DIR / "assets" / "style.css"

if css_path.exists():
    with open(css_path, "r", encoding="utf-8") as f:
        st.markdown(
            f"<style>{f.read()}</style>",
            unsafe_allow_html=True
        )

# =====================================================
# Title
# =====================================================

st.markdown(
"""
<div class="main-title">
ℹ️ Credit Risk Modeling Project
</div>

<div class="sub-title">
AI-powered Loan Default Prediction using Machine Learning
</div>
""",
unsafe_allow_html=True
)

st.divider()

# =====================================================
# Project Overview
# =====================================================

st.header("📌 Project Overview")

st.write("""
This project predicts whether a loan applicant is likely to default using a
Machine Learning model trained on the LendingClub dataset.

The objective is to help financial institutions estimate credit risk before
approving a loan application.
""")

# =====================================================
# Workflow
# =====================================================

st.divider()

st.header("⚙️ Project Workflow")

st.markdown("""
1. Collect LendingClub Dataset

2. Data Cleaning & Preprocessing

3. Handle Missing Values

4. Encode Categorical Features

5. Balance Dataset using **SMOTE**

6. Train Multiple Models

7. Select Best Random Forest Model

8. Generate Predictions

9. Explain Predictions using **SHAP**
""")

# =====================================================
# Technologies
# =====================================================

st.divider()

st.header("🛠 Technologies Used")

col1, col2 = st.columns(2)

with col1:

    st.success("""
### Programming

• Python

• Pandas

• NumPy

• Scikit-learn

• Joblib
""")

with col2:

    st.success("""
### Visualization

• Streamlit

• Plotly

• SHAP

• Matplotlib
""")

# =====================================================
# Machine Learning Pipeline
# =====================================================

st.divider()

st.header("🤖 Machine Learning Pipeline")

st.code("""
Raw Dataset
      │
      ▼
Data Cleaning
      │
      ▼
Feature Engineering
      │
      ▼
SMOTE
      │
      ▼
Random Forest Training
      │
      ▼
Prediction
      │
      ▼
SHAP Explainability
""")

# =====================================================
# Model Information
# =====================================================

st.divider()

st.header("📈 Best Model")

st.info("""
Algorithm : Random Forest Classifier

Dataset : LendingClub Loan Dataset

Balancing Method : SMOTE

Explainability : SHAP

Prediction : Probability using predict_proba()

Deployment : Streamlit
""")

# =====================================================
# Key Features
# =====================================================

st.divider()

st.header("⭐ Dashboard Features")

col1, col2 = st.columns(2)

with col1:

    st.markdown("""
✅ Loan Risk Prediction

✅ Approval Probability

✅ Risk Meter

✅ Loan Decision

✅ Model Performance
""")

with col2:

    st.markdown("""
✅ Feature Importance

✅ SHAP Explainability

✅ Interactive Charts

✅ Professional Dashboard

✅ Download Prediction Report
""")

# =====================================================
# Disclaimer
# =====================================================

st.divider()

st.warning("""
This dashboard is developed for educational and research purposes.

The prediction is generated by a trained Machine Learning model and should be
used only as a decision-support tool.

The final loan approval decision depends on the financial institution's
verification process and lending policies.
""")